
main:
  chain: chain_llm #选择的链路
  live2d_unity_system: true
  clear_log_history_pic: true #是否每次重启时清空日志
  clear_log_history_gui: true #是否每次重启时清空日志

message_get:
  system: on #整个监听系统开启或关闭，on or off
  #前端框架
  ui_tkinter: true
  ui_streamlit: false #ui界面是否使用streamlit

  #文本
  is_text: true #是否启用响应监听

  #摄像头
  is_pic: true #是否启用响应监听
  pic_interval_time: 12 #间隔多少秒一次图像记录
  pic_window_width: 540 #窗口尺寸 pic&gui: 27寸720:520：420，24寸540:390:315
  pic_window_height: 390
  pic_save_path: log/history/message_get/pic
  #屏幕
  is_gui: false #是否启用响应监听
  gui_interval_time: 16
  gui_window_width: 540
  gui_window_height: 315
  gui_save_path: log/history/message_get/gui
  #麦克风音频
  is_micro: true
  micro_interval_time: 10 #每隔多少秒做一轮语音识别（语音转文本）
  #电脑内音频
  is_voice: false #是否启用响应监听
  voice_interval_time: 10 #每隔多少秒做一轮语音识别（语音转文本）



is_chain: true #是否进行全链路推理

get_input:
  response_interval_time: 20 #每次响应间隔时间
  get_length: 10 #截取多长的监听信息作为输入
  #性格
  character: 乐于接收新事物，充满好奇 #自定义的性格
  #记忆
  short_memory_length: 1 #短期记忆长度
  long_memory_update_num: 5 #last_content容量，即每多少轮对话更新一次长期记忆

input_action: null

input_think: null

think_action: null

action_output: null

